### ISSUE TITLE
Distillation with ResNet-50

### ISSUE THREAD

**Issue by VincentHu19** [bbbdylan/unisiam#2]
I just reproduced your project on miniImageNet. Wonderful work! 
But I've got a question, have you used ResNet-50 for knowledge distillation in your miniImageNet experiments, and how do the results compare to ResNet-18/ResNet-34. I didn't find it in the paper. Looking forward to your reply!

**Comment by VincentHu19** [comment]
> I just reproduced your project on miniImageNet. Wonderful work! But I've got a question, have you used ResNet-50 for knowledge distillation in your miniImageNet experiments, and how do the results compare to ResNet-18/ResNet-34. I didn't find it in the paper. Looking forward to your reply!

I mean using ResNet-50 as student's backbone.

**Comment by lynlynlyn** [comment]
Are you referring to the performance of the resent-50 **without** distillation? Or the performance of resnet-50 **with** distillation?

**Comment by VincentHu19** [comment]
I mean the performance of resnet-50 with distillation. Thanks for your timely reply!

**Comment by lynlynlyn** [comment]
In our preliminary experiments, distilling resnet50 with resnet50 will slightly improve performance.

**Comment by VincentHu19** [comment]
I got it. Best wishes!
