### ISSUE TITLE
您好，打扰了，如果只想运行测试功能，具体我应该怎么做呢？

### ISSUE THREAD

**Issue by xiaoxuesheng180** [bbbdylan/unisiam#3]

**Comment by lynlynlyn** [comment]
download (trained) checkpoints from Google Drive and run train.py with the --eval_path option, which represents the checkpoint path of test model.

**Comment by xiaoxuesheng180** [comment]
我已经收到你的邮件！

**Comment by xiaoxuesheng180** [comment]
> 从 Google 云端硬盘下载（训练）检查点，并使用 --eval_path 选项运行 train.py，该选项表示测试模型的检查点路径。

python ./train.py --data_path .\dataset\mini\miniimagenet --eval_path mini_r18.pth，打扰了，十分感谢您的回答，请问不知道是不是这样子

**Comment by bbbdylan** [comment]
Please make sure that you are able to train, i.e., the running environment is correct, before testing.
