### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by xiaoxuesheng180** [bbbdylan/unisiam#4]
FileNotFoundError: [Errno 2] No such file or directory: '.datasetminiminiimagenetimages/images/n0212916500000959.jpg'
您好，请问我感觉数据和路径都没问题，为什么会有这样的情况呢？

**Comment by bbbdylan** [comment]
Please make sure that you are able to train, i.e., the running environment is correct, before testing.

**Comment by xiaoxuesheng180** [comment]
> Please make sure that you are able to train, i.e., the running environment is correct, before testing.

您好，以下是我的运行环境，是否可行呢
镜像：Py Torch 1.11.0Python 3.8(ubuntu20.04)Cuda 11.3
GPU：RTX 3090(24GB)*4
CPU：60 vCPU AMD EPYC 7543 32-Core Processor
内存：320GB
在训练和测试都出现了同样的情况，为什么每次运行都是文件或者图像不存在，而且错误情况的图片不固定，可是数据本身没有问题。
测试时，也有将def build_train_loader中的partition='train',改成test。我不太清楚到底哪里出现了问题，不知道您可否帮助我一下，万分感谢。

**Comment by bbbdylan** [comment]
Please check your data path (--data_path) carefully. In addition, for testing, you do NOT need to change any code. 

Please use English to make  your question helpful to others.

**Comment by xiaoxuesheng180** [comment]
> 请仔细检查您的数据路径 （--data_path）。此外，对于测试，您无需更改任何代码。
> 
> 请使用英语使您的问题对其他人有所帮助。

Ok, thank you very much for your answer. I'll try again.
May I ask if I want to change a small data set for debugging (such as WHU-RS19, or is there a suitable small data set recommendation), do I need to change the format and size of the images in the code?

**Comment by xiaoxuesheng180** [comment]
> Please check your data path (--data_path) carefully. In addition, for testing, you do NOT need to change any code.
> 
> Please use English to make your question helpful to others.

Thank you. I've found the problem. I'm on the wrong path. On Linux/MacOS, paths use slashes/splits. So -- data_path. /dataset/mini is correct. In Windows, paths are split by backslash \, so -- data_path. \dataset\mini should be used.
Now, it's running, and I'm wondering how long does it probably take to run a test? Is it normal to have no reaction for a long time.Thank you for your answer
