### ISSUE TITLE
pre-trained models' issue

### ISSUE THREAD

**Issue by richouli** [bbbdylan/unisiam#6]
Hi! 
Greet job first! Thanks for your efforts.
I ran on my computer but didn’t get the desired results. Could you please share the configuration information for the pre-trained models?

**Comment by richouli** [comment]
Also, I found feature zt is torch.Size([512, 512]) but ds is torch.Size([512, 2048]).(zt and ds are from Projection(Teacher) and Distillation seperately)
![image](https://github.com/bbbdylan/unisiam/assets/104425476/a6411844-0e18-4d6b-90df-f809aaac25d9)
Did I make a mistake at some point? Really hope to get help

**Comment by lynlynlyn** [comment]
1. All configs can be found in https://github.com/bbbdylan/unisiam/tree/main/config.
2. Make sure to use the same config as 1
