### ISSUE TITLE
Cant reproduce results with pre-trained models

### ISSUE THREAD

**Issue by CHeggan** [bbbdylan/unisiam#7]
Hi there, 

I am currently trying to utilise your approach. More specifically I am trying to use your pre-trained models as porvided here (https://drive.google.com/drive/folders/1N_5ZiI73TfFFFOudWDPuNXeYc2dHzKYU). 

Currently, I am attempting to use your codebase as cloned with the pre-trained 'mini_r18.pth' model. Using this model for evaluation via 

```
python ./train.py --data_path D:\Downloads\miniimagenet\miniimagenet --eval_path mini_r18.pth
```

results in significantly lower performance than what is stated in the original paper, see below:

![image](https://github.com/bbbdylan/unisiam/assets/38021095/15af1c20-daaa-4dc5-a89e-29b110f68a6c)

Environment details: From what I can gather, a requirements or reproducible environment file is not supplied with the repo, however I have done my best to reproduce based on your other closed issues. I am using pytorch 1.8 with cuda 10.2 and python 3.7

Any help with rectifying or explaining this difference in obtained performance would be greatly appreciated!

Cheers!

**Comment by bbbdylan** [comment]
It looks like the performance of a random initialization of the network. Make sure you load the model correctly.

**Comment by CHeggan** [comment]
The model is loaded and used through your script (I am not using any custom code or re-implementations), if an issue is occurring with model loading it is in there. Can you confirm the model loading is working as intended with local reproduction?

**Comment by bbbdylan** [comment]
The program hasn't provided any official scripts for evaluation, which might be provided in the future. Considering that it looks like someone   (#1 , #2) else has already reproduced it correctly, please make some attempts to make it possible to load the model correctly.

**Comment by bbbdylan** [comment]
I just successfully reproduced it in a completely new environment with cmd:

`python train.py --eval_path <correct-checkpoint-path> --data_path  <correct-data-path>
`

Here are the main environments:

Linux + python 3.9 + CUDA11.7
torch 1.13.0+cu117
torchvision 0.14.0+cu117
scikit-learn 1.3.2
Pillow 10.1.0
numpy 1.26.2

I'm inclined to think it's the windows environment that's causing some of the loading errors, in fact, I've never tested it in a windows environment. Make sure you  have and load the correct dataset and model.

**Comment by CHeggan** [comment]
Appreciate you checking this, I will try with linux and see how it goes!
